packages:
  - "apps/*"
peerDependencyRules:
  allowAny:
    # for tsconfck and openapi-typescript, consider remove in the future
    - typescript
    # for crossws, consider remove in the future
    - srvx
allowBuilds:
  "@swc/core": true
  core-js: true
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
