[project]
name = "eats"
revision = "1.0"

[providers]
local = "dotenv://.env"
openbao = "openbao://secrets.scottylabs.org/secret"

[profiles.default]
#######
# web #
#######
MAPKIT_ALLOWED_ORIGINS = { description = "" }
MAPKIT_JS_AUTH_KEY = { description = "" }
MAPKIT_JS_KEY_ID = { description = "" }
MAPKIT_JS_TEAM_ID = { description = "" }
VITE_API_URL = { description = "backend url, possible values: local, http://localhost:5010, https://api.staging.cmueats.com" }
VITE_POSTHOG_KEY = { description = "" }

##############
# dining-api #
##############
PORT = { description = "" }
NUMBER_OF_SCRAPES = { description = "" }
SLACK_BACKEND_WEBHOOK_URL = { description = "" }
SLACK_FRONTEND_WEBHOOK_URL = { description = "" }
SLACK_MAIN_CHANNEL_WEBHOOK_URL = { description = "" }
INTER_SCRAPE_WAIT_INTERVAL = { description = "" }
RELOAD_WAIT_INTERVAL = { description = "" }
DATABASE_URL = { description = "" }
NODE_ENV = { description = "" }
ENV = { description = "" }
OIDC_SERVER = { description = "" }
OIDC_CLIENT_ID = { description = "" }
OIDC_CLIENT_SECRET = { description = "" }
SESSION_COOKIE_SIGNING_SECRET = { description = "" }
GOOGLE_CLIENT_ID = { description = "" }
GOOGLE_CLIENT_SECRET = { description = "" }
GOOGLE_REFRESH_TOKEN = { description = "" }
ALERT_EMAIL_SEND = { description = "" }
ALERT_EMAIL_CC = { description = "" }
DEV_DONT_FETCH = { description = "set this to false to update the database on startup" }
